FROM python:3.11

WORKDIR /app
COPY . /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r ./requirements.txt


CMD uwsgi --http 127.0.0.1:8000 --master -p 4 --wsgi-file app.wsgi